site_name:  Workout Controler - Woco
repo_name: 'Woco'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'
    palette:
      primary: black


docs_dir: ../docs/
site_dir: ../docs/
